### ISSUE TITLE
Finais

### ISSUE THREAD

**Issue by vinmh** [TV-Azul-Studios/canal-1#11]
5 finais = Bom-SemFuga, Bom-Fuga, Mau-SemFuga1,Mau-SemFuga2 , Mau-Fuga

**Comment by thagiat** [comment]
Bom-SemFuga : Por ter cometido o crime de assassinato ele passa um tempo na cadeia. Quando se torna um homem livre, consegue viver pacificamente na região.

**Comment by vinmh** [comment]
Bom-Fuga: Ele consegue fugir para uma região onde ele não é reconhecido orientado pelo filho do MacGuffin/Vítima  e assim consegue recomecar sua vida.

**Comment by vinmh** [comment]
Mau-Fuga: Usando a rota de fuga adquirida no decorrer do jogo, ele foge, mas como não tem idéia do mundo afora, ele segue sem rumo e constantemente perseguido pelos seus terríveis crimes pelo resto de sua vida.

**Comment by thagiat** [comment]
Mau-SemFuga1: Logo após decidir continuar na cidade ele acaba sendo desafiado pelo filho do MacGuffin/Vítima, se o jogador perde a luta,  Death to the Hero!!

**Comment by thagiat** [comment]
Mau-SemFuga2: Logo após decidir continuar na cidade ele acaba sendo desafiado pelo filho do MacGuffin/Vítima, se o jogador ganha a luta,  o Herói assume o lugar do príncipe e entra em um lento plano para tornar a vida dos seus súditos um inferno.
